services:
  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk
      - SPLUNK_PASSWORD
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}@splunk.com
      - SPLUNKBASE_PASSWORD
      # - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/4353/release/1.7.16/download,https://splunkbase.splunk.com/app/7538/release/1.1.0/download,https://splunkbase.splunk.com/app/7539/release/1.1.0/download
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/4353/release/1.7.16/download,https://splunkbase.splunk.com/app/7539/release/1.1.0/download,/tmp/config/splunk/TA_cisco_catalyst-D-1.1.1-3.spl
      - SPLUNK_HEC_TOKEN
      - TZ=${TZ:-Europe/Brussels}
    volumes:
      # - ./patch/props.conf:/opt/splunk/etc/apps/TA_cisco_catalyst/local/props.conf
      - ./config/splunk/:/tmp/config/splunk/
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"

  splunk-config:
    image: curlimages/curl:latest # Use the official curl image
    environment:
      - SPLUNK_HOST=splunk
      - SPLUNK_USERNAME=admin
      - SPLUNK_PASSWORD
      - DNAC_HOST
      - DNAC_USERNAME
      - DNAC_PASSWORD
      - TZ=${TZ:-Europe/Brussels}
    depends_on:
      splunk:
        condition: service_healthy
    volumes:
      - ./config/splunk:/config
    entrypoint: ["/bin/sh", "/config/initialize.sh"]