services:
  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=splunk
      - SPLUNK_PASSWORD
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}@splunk.com
      - SPLUNKBASE_PASSWORD
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/4353/release/1.7.16/download,https://splunkbase.splunk.com/app/7538/release/1.1.0/download,https://splunkbase.splunk.com/app/7539/release/1.1.0/download
      - SPLUNK_HEC_TOKEN
      - TZ=${TZ:-Europe/Brussels}
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"